[build-system]
requires = ["setuptools>=62.6.0", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = ["--cov=raw2tmap", "--cov-report=xml:coverage.xml"]
testpaths = ["tests"]

[tool.ruff]
select = ["E", "F", "I"]

[tool.setuptools_scm]
